-- ============================================================
-- PPL Flashcards — Supabase setup
-- Run this once in your Supabase project:
--   Dashboard > SQL Editor > New query > paste > Run
-- ============================================================

-- 1. Table holding all card metadata (small — no images here)
create table if not exists public.flashcards (
    id                  integer primary key,
    question            text not null,
    answer_text         text,
    answer_image        text,            -- public URL to an image in Storage (or null)
    total_correct       integer not null default 0,
    total_wrong         integer not null default 0,
    consecutive_correct integer not null default 0,
    archived            boolean not null default false,
    created_date        text,
    history             jsonb not null default '[]'::jsonb
);

-- 2. Storage bucket for the (few) answer images.
--    Public bucket => images load with a plain URL, no signed links needed.
insert into storage.buckets (id, name, public)
values ('flashcard-images', 'flashcard-images', true)
on conflict (id) do nothing;

-- 3. Single-row table that remembers the "resume position" (current card,
--    study mode) so it follows you across devices.
create table if not exists public.app_state (
    id                  integer primary key default 1,
    current_card_index  integer not null default 0,
    study_mode          text not null default 'active'
);

insert into public.app_state (id, current_card_index, study_mode)
values (1, 0, 'active')
on conflict (id) do nothing;

-- 4. Migration: make id auto-increment so two devices creating a card at
--    the same time can never collide/overwrite each other. Safe to run
--    even if you already have rows — it keeps existing ids and starts
--    the auto-increment counter after the current max id.
alter table public.flashcards
    alter column id add generated by default as identity;

select setval(
    pg_get_serial_sequence('public.flashcards', 'id'),
    (select coalesce(max(id), 0) from public.flashcards)
);

-- ============================================================
-- Notes:
-- * The app connects with the SERVICE_ROLE key (kept in st.secrets),
--   which bypasses row-level security, so no RLS policies are needed.
-- * If you'd rather use the anon key, enable RLS and add permissive
--   policies — but service_role is simpler for a single-user app.
-- ============================================================
